FROM jenkins/jenkins:lts

USER root

# Instalar Docker + docker compose
RUN apt-get update && apt-get install -y docker.io docker-compose

# 🔥 AGREGAR ESTO
RUN usermod -aG docker jenkins

USER jenkins