events {}
http {
    upstream backend {
        server app-blue:3000; # Default to blue
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}