events {}

http {
  upstream app {
    server app-blue:3000;  # 🔵 por defecto inicia en blue
  }

  server {
    listen 80;

    location / {
      proxy_pass http://app;
    }

    location /health {
      proxy_pass http://app/health;
    }
  }
}